"""Static ranking configuration extracted from the Redrob challenge bundle.

The values here intentionally favor demonstrated production retrieval/ranking
work over broad AI keyword presence. The ranker is deterministic and uses only
local candidate data during scoring.
"""

from __future__ import annotations

from datetime import date

REFERENCE_DATE = date(2026, 6, 17)

TOP_K = 100
HEAP_KEEP_SIZE = 300

CONSULTING_COMPANIES = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "mindtree",
    "ltimindtree",
    "hcl",
    "tech mahindra",
    "mphasis",
}

PRODUCT_COMPANIES = {
    "swiggy",
    "cred",
    "razorpay",
    "zomato",
    "flipkart",
    "meesho",
    "inmobi",
    "nykaa",
    "zoho",
    "freshworks",
    "vedantu",
    "ola",
    "paytm",
    "byju's",
    "upgrad",
    "policybazaar",
    "dream11",
    "pharmeasy",
    "phonepe",
    "unacademy",
    "sarvam ai",
    "haptik",
    "yellow.ai",
    "observe.ai",
    "verloop.io",
    "mad street den",
    "glance",
    "krutrim",
    "saarthi.ai",
    "locobuzz",
    "google",
    "meta",
    "amazon",
    "microsoft",
    "netflix",
    "linkedin",
    "salesforce",
    "hooli",
    "pied piper",
    "initech",
}

AI_PRODUCT_COMPANIES = {
    "sarvam ai",
    "haptik",
    "yellow.ai",
    "observe.ai",
    "verloop.io",
    "mad street den",
    "krutrim",
    "saarthi.ai",
    "locobuzz",
    "genpact ai",
    "aganitha",
    "rephrase.ai",
    "niramai",
    "wysa",
}

COMPANY_FOUNDING_YEARS = {
    "cred": 2018,
    "razorpay": 2014,
    "swiggy": 2014,
    "zomato": 2008,
    "flipkart": 2007,
    "meesho": 2015,
    "inmobi": 2007,
    "nykaa": 2012,
    "zoho": 1996,
    "freshworks": 2010,
    "vedantu": 2011,
    "ola": 2010,
    "paytm": 2010,
    "byju's": 2011,
    "upgrad": 2015,
    "policybazaar": 2008,
    "dream11": 2008,
    "pharmeasy": 2015,
    "phonepe": 2015,
    "unacademy": 2015,
    "sarvam ai": 2023,
    "krutrim": 2023,
    "haptik": 2013,
    "yellow.ai": 2016,
    "observe.ai": 2017,
    "verloop.io": 2015,
    "mad street den": 2016,
    "glance": 2019,
    "saarthi.ai": 2017,
    "niramai": 2016,
    "rephrase.ai": 2018,
    "wysa": 2015,
    "google": 1998,
    "meta": 2004,
    "amazon": 1994,
    "microsoft": 1975,
    "netflix": 1997,
    "salesforce": 1999,
    "linkedin": 2003,
}

TITLE_WEIGHTS = {
    "senior ai engineer": 1.55,
    "lead ai engineer": 1.50,
    "staff machine learning engineer": 1.48,
    "senior machine learning engineer": 1.42,
    "recommendation systems engineer": 1.38,
    "search engineer": 1.34,
    "machine learning engineer": 1.22,
    "applied ml engineer": 1.20,
    "senior software engineer (ml)": 1.12,
    "senior applied scientist": 1.10,
    "senior nlp engineer": 1.08,
    "ai engineer": 1.05,
    "nlp engineer": 0.98,
    "ml engineer": 0.82,
    "senior data scientist": 0.76,
    "data scientist": 0.58,
    "ai research engineer": 0.35,
    "junior ml engineer": 0.25,
    "ai specialist": 0.20,
    "computer vision engineer": 0.10,
}

TECH_TITLE_HINTS = (
    "backend",
    "platform",
    "software",
    "data engineer",
    "analytics engineer",
    "cloud engineer",
    "devops",
)

NON_TECH_TITLES = {
    "marketing manager",
    "hr manager",
    "accountant",
    "sales executive",
    "graphic designer",
    "civil engineer",
    "mechanical engineer",
    "customer support",
    "operations manager",
    "content writer",
    "business analyst",
    "project manager",
}

TIER1_LOCATION_HINTS = (
    "pune",
    "noida",
    "delhi",
    "gurgaon",
    "gurugram",
    "mumbai",
    "hyderabad",
    "bangalore",
    "bengaluru",
)

RANKING_TERMS = (
    "ranking",
    "ranker",
    "learning-to-rank",
    "re-ranking",
    "reranking",
    "recommendation system",
    "recommendations-heavy",
    "recommendation",
    "recommender",
    "discovery feed",
    "search product",
    "search and discovery",
    "surface relevant",
    "relevance",
    "matching",
)

RETRIEVAL_TERMS = (
    "embedding",
    "embeddings",
    "semantic search",
    "vector search",
    "dense retrieval",
    "hybrid",
    "faiss",
    "pinecone",
    "qdrant",
    "weaviate",
    "milvus",
    "bge",
    "sentence-transformer",
    "nearest-neighbor",
    "bm25",
    "index refresh",
    "index versioning",
    "embedding drift",
)

EVAL_TERMS = (
    "ndcg",
    "mrr",
    "offline evaluation",
    "online correlation",
    "a/b",
    "ab test",
    "relevance judgments",
    "human judgments",
    "offline-online",
    "evaluation framework",
    "eval harness",
    "metric correlation",
)

PRODUCTION_TERMS = (
    "production",
    "shipped",
    "serving",
    "deployed",
    "real users",
    "queries",
    "latency",
    "p95",
    "scale",
    "rollback",
    "monitoring",
    "dashboards",
    "feature pipeline",
    "feedback loop",
)

HR_TECH_TERMS = (
    "candidate-jd",
    "candidate corpus",
    "recruiter-facing",
    "recruiter engagement",
    "time-to-shortlist",
    "recruiter-feedback",
    "candidate matching",
)

SELF_LEARNER_TERMS = (
    "curious about how ai",
    "experimented with chatgpt",
    "online courses",
    "side project",
    "langchain",
    "openai api",
    "exploring ai",
    "self-learner",
)

SKILL_GROUPS = {
    "retrieval": (
        "embeddings",
        "sentence transformers",
        "vector search",
        "semantic search",
        "information retrieval",
        "faiss",
        "pinecone",
        "qdrant",
        "weaviate",
        "milvus",
        "elasticsearch",
        "opensearch",
    ),
    "ranking": (
        "recommendation systems",
        "learning to rank",
        "xgboost",
        "lightgbm",
        "search relevance",
    ),
    "mlops": (
        "mlops",
        "bentoml",
        "mlflow",
        "kubeflow",
        "kubernetes",
        "docker",
        "fastapi",
    ),
    "llm": (
        "llms",
        "fine-tuning llms",
        "lora",
        "qlora",
        "hugging face transformers",
        "rag",
        "nlp",
    ),
    "python": (
        "python",
        "sql",
        "spark",
        "airflow",
        "data pipelines",
    ),
}

SKILL_GROUP_WEIGHTS = {
    "retrieval": 0.55,
    "ranking": 0.35,
    "mlops": 0.22,
    "llm": 0.22,
    "python": 0.18,
}

RELEVANT_SKILLS_FOR_REASONING = {
    "python",
    "embeddings",
    "sentence transformers",
    "vector search",
    "semantic search",
    "information retrieval",
    "faiss",
    "pinecone",
    "qdrant",
    "weaviate",
    "milvus",
    "elasticsearch",
    "opensearch",
    "recommendation systems",
    "xgboost",
    "lightgbm",
    "mlops",
    "bentoml",
    "mlflow",
    "kubeflow",
    "fastapi",
    "rag",
    "llms",
    "fine-tuning llms",
    "lora",
    "nlp",
}
